- alias: Morning - Weekend - Stage 2
  hide_entity: True
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
        - sat
        - sun
    - condition: state
      entity_id: group.family
      state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.living_room
      data:
        color_temp: 200
        brightness: 254
    - service: light.turn_on
      entity_id: light.pantry
      data:
        brightness: 255
        transition: 60
    - condition: state
      entity_id: group.tristal
      state: 'home'   
    - service: light.turn_on
      entity_id: light.master_bedroom
      data:
        color_temp: 200
        brightness: 254
        transition: 1800
    - service: lock.unlock
      entity_id: lock.back_door
    - service: script.fan_on
    - service: media_player.media_stop
      entity_id: 
        - media_player.master_suite
    - service: media_player.volume_set
      entity_id: media_player.master_suite
      data: 
        volume_level: 0.40
    - service: media_player.turn_off
      entity_id: 
        - media_player.master_suite
