- alias: Morning - Weekend - Stage 1
  hide_entity: True
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
        - sat
        - sun
    - condition: state
      entity_id: group.tristal
      state: 'home'
    - condition: state
      entity_id: light.master_bedroom
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.master_bedroom
      data:
        color_temp: 200
        brightness: 50
        transition: 60
