- alias: Rain - Exterior Lights - Stop
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.rain
      to: 'off'
      for:
        minutes: 20
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: 8
  action:
    - service: light.turn_off
      entity_id: light.front_door
      data:
        transition: 60
    - service: light.turn_off
      entity_id: light.flood_lights
