- alias: Rain Unoccupied Stop
  trigger:
    - platform: state
      entity_id: binary_sensor.rain
      to: 'off'
      for:
        minutes: 20
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: 8
    - condition: state
      entity_id: group.family
      state: 'not_home'
  action:
    - service: light.turn_off
      entity_id: 
        - light.living_room_lights
      data:
        transition: 60
