- alias: Bias Light On
  trigger:
    - platform: state
      entity_id: media_player.vizio_smartcast
      to: 'on'
    - platfrom: state
      entity_id: switch.livingroom_speaker
      from: 'off'
      to: 'on'
 #   - platform: state
 #     entity_id: remote.livingroom
 #     to: 'on'
  condition:
    - condition: state
      entity_id: light.bias_light
      state: 'off'
  action: 
    - service: light.turn_on
      entity_id: light.bias_light
      data:
        transition: 5
        brightness: 175
      data_template:
        color_temp: >
          {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            300
          {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
            250
          {% else %}
          {% endif %}
        
- alias: Bias Light Off
  trigger:
    - platform: state
      entity_id: media_player.vizio_smartcast
      to: 'off'
    - platform: state
      entity_id: switch.livingroom_speaker
      from: 'off'
      to: 'on'
#    - platform: state
#      entity_id: remote.livingroom
#      to: 'off'
  condition:
    - condition: state
      entity_id: light.bias_light
      state: 'on'
  action: 
    - service: light.turn_off
      entity_id: light.bias_light
      data:
        transition: 10

- alias: Bias Light Fade
  trigger:
    platform: time
    at: '9:30:00'
  condition:
    - condition: state
      entity_id: light.bias_light
      state: 'on'
    - condition: template
      value_template: '{{ states.light.bias_light.attributes.color_temp == 200 }}'
  action:
    - service: light.turn_on  
      entity_id: light.bias_light
      data:
        color_temp: 250
        brightness: 175
        transition: 1800
