- alias: Sunset Unoccupied
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 8
  condition:
    - condition: state
      entity_id: light.living_room_lights
      state: 'off'
    - condition: state
      entity_id: group.family
      state: 'not_home'
  action:
    - service: light.turn_on
      entity_id: light.living_room_lights
      data:
        color_temp: 366
        brightness: 150
        transition: 600
    - service: switch.turn_on
      entity_id: switch.nightlight
      
