- alias: home away assist - off
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.wan_up
      to: 'off'
  action:
    service: automation.turn_off
    entity_id:
      - automation.away_mode__bedroom
      - automation.away_mode__general
      - automation.home_mode__bedroom
      - automation.home_mode__general
      - automation.home_mode__livingroom
      
- alias: home away assist - off
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.wan_up
      to: 'on'
  action:
    service: automation.turn_on
    entity_id:
      - automation.away_mode__bedroom
      - automation.away_mode__general
      - automation.home_mode__bedroom
      - automation.home_mode__general
      - automation.home_mode__livingroom
