# - alias: Harmony
#   trigger:
#     platform: state
#     entity_id: input_select.harmony
#     from: 'Select Input'
#   action:
#     - service: remote.turn_on
#       entity_id: remote.livingroom
#       data_template:
#         activity: >
#           {% if is_state("input_select.harmony", "Play Switch") %}
#             39577141
#           {% elif is_state("input_select.harmony", "Watch Android TV") %}
#             43103950
#           {% else %}
#           {% endif %}
#     - service: input_select.select_option
#       entity_id: input_select.harmony
#       data_template:
#         option: "Select Input"

#- alias: Harmony Off
#  trigger:
#    platform: state
#    entity_id: input_select.harmony
#    to: 'Power Off'
#  action:
#    - service: remote.turn_off
#      entity_id: remote.livingroom
#    - service: input_select.select_option
#      entity_id: input_select.harmony
#      data_template:
#        option: "Select Input"

# - alias: Harmony Light Control Start
#   trigger: 
#     - platform: state
#       entity_id: input_boolean.harmony_lighting_control
#       from: 'off'
#       to: 'on'
#     - platform: state
#       entity_id: media_player.plex_shield_android_tv
#       to: 'playing'
#   condition:
#     - condition: state
#       entity_id: input_boolean.harmony_lighting_control
#       state: 'on'
#     - condition: state
#       entity_id: light.living_room_lights
#       state: 'on'
#     - condition: numeric_state
#       entity_id: sun.sun
#       value_template: '{{ state.attributes.elevation }}'
#       below: 12
#     - condition: state
#       entity_id: input_boolean.movie_mode
#       state: 'off'
#     - condition: template
#       value_template: >
#         {% if states.media_player.plex_shield_android_tv.state == "playing" %}
#           {{ states.media_player.plex_shield_android_tv.state == "playing" and states.media_player.plex_shield_android_tv.attributes.app_name in ["Movies", "UHD Movies"] and states.media_player.plex_shield_android_tv.attributes.media_content_rating in ["PG-13", "R", "NC-17", "Unrated", "TV-MA"]}}
#         {% else %}}
#           true
#         {% endif %}
#   action:
#     - service: input_number.set_value
#       entity_id: input_number.harmony_dim
#       data_template:
#         value: '{{states.sensor.brightness_lr.state}}'
#     - service: light.turn_on
#       entity_id: light.living_room_lights
#       data_template:
#         brightness: >
#           {% if states.input_number.harmony_dim.state|int >=60 %}
#             60
#           {% else %}
#             {{ states.input_number.harmony_dim.state }}
#           {% endif %}
#         color_temp: >
#           {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
#             500
#           {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
#             200
#           {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
#             500
#           {% elif states.sun.sun.attributes.elevation < 8 %}
#             366
#           {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
#             300
#           {% else %}
#           {% endif %}
#     - service: light.turn_on
#       entity_id: light.bias_light
#       data_template:
#         color_temp: >
#           {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
#             500
#           {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
#             200
#           {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
#             500
#           {% elif states.sun.sun.attributes.elevation < 8 %}
#             300
#           {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
#             250
#           {% else %}
#           {% endif %}
      
# - alias: Harmony Light Control End
#   trigger: 
#     - platform: state
#       entity_id: media_player.plex_shield_android_tv
#       to: 
#         - 'paused'    
#         - 'stopped'
#         - 'idle'
#   condition: 
#     - condition: or
#       conditions:
#         - condition: state
#           entity_id: sensor.current_activity
#           state: 'Play Switch'
#         - condition: state
#           entity_id: sensor.current_activity
#           state: 'PowerOff'
#         - condition: state
#           entity_id: sensor.current_activity
#           state: 'Watch Android TV'
#     - condition: state
#       entity_id: light.living_room_lights
#       state: 'on'
#     - condition: numeric_state
#       entity_id: sun.sun
#       value_template: '{{ state.attributes.elevation }}'
#       below: 12
#     - condition: state
#       entity_id: input_boolean.movie_mode
#       state: 'off'
#     - condition: state
#       entity_id: input_boolean.goodnight_initiated
#       state: 'off'
#   action: 
#     service: light.turn_on
#     entity_id: light.living_room_lights
#     data:
#       transition: 3
#     data_template:
#       brightness:
#         '{{states.input_number.harmony_dim.state | int }}'
#       color_temp: >
#           {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
#             500
#           {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
#             200
#           {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
#             500
#           {% elif states.sun.sun.attributes.elevation < 8 %}
#             366
#           {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
#             300
#           {% else %}
#           {% endif %}

# - alias: Harmony Lighting Control Off
#   trigger: 
#     - platform: state
#       entity_id: input_boolean.harmony_lighting_control
#       from: 'on'
#       to: 'off'
#   action: 
#     service: light.turn_on
#     entity_id: light.living_room_lights
#     data_template:
#       brightness: 
#         '{{ states.input_number.harmony_dim.state | int }}'

#- alias: Harmony Cast Control Start
#  trigger: 
#    - platform: state
#      entity_id: media_player.shield_tv
#      to: 'playing'
#  condition:
#    condition: template
#    value_template: "{{ states.sensor.current_activity.state != 'Watch Android TV'}}"
#  action: 
#    - service: remote.turn_on
#      entity_id: remote.livingroom
#      data:
#        activity: 43103950
        
#- alias: Harmony Gaming Control Start
#  trigger: 
#    - platform: template
#      value_template: "{{ states.media_player.vizio_smartcast.attributes.source == 'HDMI-3' }}"
#  condition:
#    condition: template
#    value_template: "{{ states.sensor.current_activity.state != 'Play Switch'}}"   
#  action: 
#    - service: remote.turn_on
#      entity_id: remote.livingroom
#      data:
#        activity: 39577141
        
- alias: Movie Mode Start
  trigger: 
    platform: state
    entity_id: input_boolean.movie_mode
    from: "off"
    to: "on"
  action: 
    - service: input_number.set_value
      entity_id: input_number.movie_mode
      data_template:
        value: '{{states.sensor.brightness_lr.state}}'
    - service: light.turn_off
      entity_id:
        - light.table_lamp
        - light.cabinet_lights
        - light.recessed_lights
        - light.pantry
      data:
        transition: 15
    - service: switch.turn_off
      entity_id: 
        - switch.overhead_light
        - switch.chandelier
    - service: light.turn_on
      entity_id:
        - light.floor_lamp_left
        - light.floor_lamp_right
      data:
        brightness: 60
        color_temp: 500
        transition: 15
    - service: light.turn_on
      entity_id: light.bias_light
      data:
        color_temp: 500
        transition: 15
        brightness: 175
        
- alias: Movie Mode Stop
  trigger: 
    platform: state
    entity_id: input_boolean.movie_mode
    from: "on"
    to: "off"
  action:
    - service: light.turn_on
      data:
        transition: 15
      data_template:
        entity_id: >
          {% if states.input_number.movie_mode.state | int == (states.light.floor_lamp_left.attributes.brightness | int + states.light.floor_lamp_right.attributes.brightness | int) /2%}
            light.table_lamp
          {% else %}
            light.living_room_lights
          {% endif %}
        brightness:
          '{{ states.input_number.movie_mode.state | int }}'
        color_temp: >
          {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            366
          {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
            300
          {% else %}
          {% endif %}
    - service: light.turn_on
      entity_id: 
        - light.pantry
        - light.cabinet_lights
      data:
        transition: 15
    - service: light.turn_on
      entity_id: light.bias_light
      data:
        transition: 15
        brightness: 175
      data_template:
        color_temp: >
          {% if (states.sensor.decimal_time.state | round(2)) <= 05.00 %}
            500
          {% elif (states.sensor.decimal_time.state | round(2)) <= 09.50 %}
            200
          {% elif (states.sensor.decimal_time.state | round(2)) >= 22.25 %}
            500
          {% elif states.sun.sun.attributes.elevation < 8 %}
            300
          {% elif (states.sensor.decimal_time.state | round(2)) > 9.50 %}
            250
          {% else %}
          {% endif %}
