- alias: Severe Weather
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.pws_alerts
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: template  
      value_template: '{{states.sensor.pws_alerts.state | int > 0}}'
    - condition: template
      value_template: '{{ states.sensor.pws_alerts.attributes.Description_WRN == "Severe Thunderstorm Warning" or states.sensor.pws_alerts.attributes.Description_TOR == "Tornado Warning" or states.sensor.pws_alerts.attributes.Description_WRN == "Winter Storm Warning" }}'
  action:
    - service: tts.google_say
      entity_id:
        - media_player.all_assistants
      data_template: 
        message: >
          Heads up. The National Weather Service has issued a 
          {% if states.sensor.pws_alerts.attributes.Description_TOR == "Tornado Warning" %}
            Tornado Warning
          {% elif states.sensor.pws_alerts.attributes.Description_WRN == "Severe Tunderstorm Warning" or states.sensor.pws_alerts.attributes.Description_WRN == "Winter Storm Warning" %}
            {{ states.sensor.pws_alerts.attributes.Description_WRN }}
          {% endif %}
            for this area.
    - service: media_player.volume_set
      entity_id: 
        - media_player.all_assistants
      data: 
        volume_level: 0.5
