- alias: Christmas Lights ON
  trigger: 
    - platform: time
      at: '07:00:00'
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 8
  condition:
    condition: template
    value_template: '{{ now().month == 12 }}'
  action:
    - service: switch.turn_on
      entity_id: switch.christmas_lights

- alias: Christmas Lights OFF
  trigger:
    - platform: time
      at: '23:59:55'
  condition: 
    condition: template
    value_template: '{{ now().month == 12 }}'      
  action:
    - service: switch.turn_off
      entity_id: switch.christmas_lights

#I don't think it ever actually triggers, but I'm leaving it on as a secondary catch to kill the lights. 
#- alias: Christmas Lights away OFF
#  trigger:
#    - platform: state
#      entity_id: group.family
#      to: "not_home"
#  condition:
#    - condition: template
#      value_template: '{{ now().month == 12 }}'
#    - condition: numeric_state
#      entity_id: sun.sun
#      value_template: '{{ state.attributes.elevation }}'
#      above: 8
#  action:
#    - service: switch.turn_off
#      entity_id: switch.christmas_lights


- id: christmas_light_panel_visiblity
  alias: 'Christmas Light Panel Visiblity'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time
      at: '00:00:00'
  action:
    service_template: >
      {% if now().month == 12 %}
        input_boolean.turn_on
      {% elif now().month != 12 %}
        input_boolean.turn_off
      {% endif %}
    entity_id: input_boolean.christmas_lights
