#- platform: rpi_gpio
#  device_class: opening
#  ports:
#    22: Bedroom Windows
#    6: Front Windows
#    27: Back Windows
#    17: Back Door
#    18: Garage Door
#    4: Front Door
- platform: mqtt
  name: "Ring Doorbell"
  state_topic: "smartthings/Front Door/button"
  qos: 0
  payload_on: "pushed"
  payload_off: "default"
  device_class: occupancy
- platform: mqtt
  name: "Front Door Motion"
  state_topic: "smartthings/Front Door/motion"
  qos: 0
  payload_on: "active"
  payload_off: "inactive"
  device_class: motion
- platform: command_line
  command: 'ping -c 1 8.8.8.8 | grep "1 received" | wc -l'
  name: 'wan_up'
  device_class: connectivity
  payload_on: 1
  payload_off: 0
  scan_interval: 60
- platform: template
  sensors:
    rain:
      value_template: '{{ states.sensor.dark_sky_icon.state == "rain"}}'
