- platform: group
  name: Front Floods
  entities:
    - light.front_flood_light_1
    - light.front_flood_light_2
- platform: group
  name: Rear Floods
  entities:
    - light.rear_flood_light_1
    - light.rear_flood_light_2
- platform: group
  name: Flood Lights
  entities:
    - light.front_floods
    - light.rear_floods
- platform: group
  name: Mancave Lights
  entities:
    - light.office_bias_light
    - light.man_cave_floor_lamp
    - light.desk_light
- platform: group
  name: Foyer
  entities:
    - light.foyer_left
    - light.foyer_right
- platform: switch
  name: Desk Light
  entity_id: switch.desk_light
- platform: group
  name: Office bias light
  entities:
    - light.office_bias_light_left
    - light.office_bias_light_right
    - light.office_bias_light_center
- platform: group
  name: Living Room Lights
  entities:
    - light.floor_lamp_left
    - light.floor_lamp_right
    - light.table_lamp
