
- platform: androidtv
  name: Shield TV
  get_sources: false
  host: 10.0.0.38
  apps: 
    com.google.android.youtube.tvunplugged: "Youtube TV"
    com.plexapp.android: "Plex"
    com.nest.android: "Nest"
    com.spotify.tv.android: "Spotify"
    com.google.android.youtube.tvkids: "Youtube Kids"
    com.amazon.amazonvideo.livingroom: "Prime Video"
    com.google.android.music: "Google Music"
    com.hulu.livingroomplus: "Hulu"
    com.google.android.youtube.tv: "YouTube"
    com.netflix.ninja: "Netflix"
    com.disney.disneyplus: "Disney Plus"
    com.hbo.hbonow: "HBO max"
  state_detection_rules: 
    'com.plexapp.android':
      - 'media_session_state'
    'com.google.android.youtube.tvunplugged':
      - 'media_session_state'
    'com.hulu.livingroomplus':
      - 'media_session_state'
    'com.google.android.tvlauncher':
      - 'standby'
    'com.amazon.amazonvideo.livingroom':
      - 'media_session_state'
    'com.netflix.ninja':
      - 'media_session_state'
    'com.disney.disneyplus':
      - 'media_session_state'
    'com.google.android.youtube.tv':
      - 'media_session_state'
    'com.hbo.hbonow':
      - 'media_session_state'
