- platform: wunderground
  api_key: 1e3e716e93f82a3c
  monitored_conditions:
    - alerts
    - weather_1d
    - precip_1d
- platform: darksky
  api_key: !secret darksky
  monitored_conditions:
    - icon
    - summary
    - precip_intensity
    - precip_probability
    - temperature
    - temperature_max
    - temperature_min
- platform: google_travel_time
  name: Drive_time_to_work
  api_key: !secret google_travel
  origin: place_id:ChIJG1SUhnKff4gRz9_GI6GdfUY
  destination: place_id:ChIJkRB9LrKFf4gRgqu8ivoA0x8
  options:
    arrival_time: '09:15:00'
- platform: template
  sensors:
    cpu:
      friendly_name: 'CPU Utilization'
      value_template: '{{ states.sensor.processor_use.state | float(1) }}'
      unit_of_measurement: '%'
    ram:
      friendly_name: 'RAM Utilization'
      value_template: '{{ states.sensor.memory_use_percent.state | float(1) }}'
      unit_of_measurement: '%'
    disk:
      friendly_name: 'Disk Utilization'
      value_template: '{{states.sensor.disk_use_percent_.state | float(1) }}'
      unit_of_measurement: '%'
    current_activity:
      friendly_name: 'Current Activity'
      value_template: '{{ states.remote.living_room.attributes.current_activity }}'
    brightness_pantry:
      value_template: '{{ states.light.pantry.attributes.brightness }}'
    brightness_lr:
      value_template: '{{ states.light.living_room.attributes.brightness }}'
    color_temp_lr:
      value_template: '{{ states.light.living_room.attributes.xy_color }}'
    color_temp_br:
      value_template: '{{ states.light.master_bedroom.attributes.xy_color }}'
    color_temp_cl:
      value_template: '{{ states.light.cabinet_lights.attributes.xy_color }}'
    time:
      value_template: '{{(now().strftime("%H") | int) + (now().strftime("%M")|int / 60) | round(2)}}'
    protect_down:
      value_template: '{% if  states.sensor.downstairs_nest_protect_battery_health.state == "Ok" and states.sensor.downstairs_nest_protect_co_status.state == "Ok" and states.sensor.downstairs_nest_protect_smoke_status.state == "Ok" %}Online{% elif states.sensor.kithen_nest_protect_co_status.state == "Emergency" or states.sensor.downstairs_nest_protect_smoke_status.state == "Emergency" %}Emergency {% elif states.sensor.downstairs_nest_protect_battery_health.state == "Replace" %}Low Battery {% else %}Error{% endif %}'    
    protect_kitchen:
      value_template: '{% if  states.sensor.kitchen_nest_protect_battery_health.state == "Ok" and states.sensor.kitchen_nest_protect_co_status.state == "Ok" and states.sensor.kitchen_nest_protect_smoke_status.state == "Ok" %}Online{% elif states.sensor.kithen_nest_protect_co_status.state == "Emergency" or states.sensor.kitchen_nest_protect_smoke_status.state == "Emergency" %}Emergency {% elif states.sensor.kitchen_nest_protect_battery_health.state == "Replace" %}Low Battery {% else %}Error{% endif %}'
    protect_up:
      value_template: '{% if  states.sensor.upstairs_nest_protect_battery_health.state == "Ok" and states.sensor.upstairs_nest_protect_co_status.state == "Ok" and states.sensor.upstairs_nest_protect_smoke_status.state == "Ok" %}Online{% elif states.sensor.kithen_nest_protect_co_status.state == "Emergency" or states.sensor.upstairs_nest_protect_smoke_status.state == "Emergency" %}Emergency {% elif states.sensor.upstairs_nest_protect_battery_health.state == "Replace" %}Low Battery {% else %}Error{% endif %}'      
    front_door:
      friendly_name: 'Front Door'
      value_template: '{% if is_state("binary_sensor.front_door", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.front_door", "off") %}mdi:crop-portrait{% else %}mdi:logout{% endif %}'
    back_door:
      friendly_name: 'Back Door'
      value_template: '{% if is_state("binary_sensor.back_door", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.back_door", "off") %}mdi:crop-portrait{% else %}mdi:logout{% endif %}'
    garage_door:
      friendly_name: 'Garage Door'
      value_template: '{% if is_state("binary_sensor.garage_door", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.garage_door", "off") %}mdi:crop-portrait{% else %}mdi:logout{% endif %}'
    front_windows:
      friendly_name: 'Front Windows'
      value_template: '{% if is_state("binary_sensor.front_windows", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.front_windows", "off") %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    back_windows:
      friendly_name: 'Back Windows'
      value_template: '{% if is_state("binary_sensor.back_windows", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.back_windows", "off") %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    bedroom_windows:
      friendly_name: 'Bedroom Windows'
      value_template: '{% if is_state("binary_sensor.bedroom_windows", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.bedroom_windows", "off") %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    huebridge:
      value_template: '{% if is_state("device_tracker.huebridge", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Hue Bridge'
    harmonyhub:
      value_template: '{% if is_state("device_tracker.harmonyhub", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Harmony Hub'
    kevobridge:
      value_template: '{% if is_state("device_tracker.kevobridge", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Kevo Bridge'
    smartthingshub:
      value_template: '{% if is_state("device_tracker.smartthingshub", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'SmartThings Hub'
    myq:
      value_template: '{% if is_state("device_tracker.myq", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'MyQ Bridge'
    macmini:
      value_template: '{% if is_state("device_tracker.macmini", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Mac Mini'
    directv_genie:
      value_template: '{% if is_state("device_tracker.directv_genie", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'DirecTv Genie'
    google_home_livingroom:
      value_template: '{% if is_state("device_tracker.google_home_livingroom", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Google Home (Livingroom)' 
    google_home_mini_kitchen:
      value_template: '{% if is_state("device_tracker.google_home_mini_kitchen", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Google Home Mini (Kitchen)'  
    google_home_mini_bedroom:
      value_template: '{% if is_state("device_tracker.google_home_mini_bedroom", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Google Home Mini (Bedroom)'
    google_home_mini_bathroom:
      value_template: '{% if is_state("device_tracker.google_home_mini_bathroom", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Google Home Mini (Bathroom)' 
    chromecast_man_cave:
      value_template: '{% if is_state("device_tracker.chromecast_man_cave", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Chromecast (Man Cave)'
    chromecast_audio_dining_room:
      value_template: '{% if is_state("device_tracker.chromecast_audio_dining_room", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Chromecast Audio (Dining Room)'
    chromecast_audio_garage:
      value_template: '{% if is_state("device_tracker.chromecast_audio_garage", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Chromecast Audio (Garage)'  
    viziocrave360:
      value_template: '{% if is_state("device_tracker.viziocrave360", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Vizio Crave 360' 
    vizio_m70e3:
      value_template: '{% if is_state("device_tracker.vizio_m70e3", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Vizio M70'
    lg_sj9:
      value_template: '{% if is_state("device_tracker.lg_sj9", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'LG SJ9' 
    rasplex:
      value_template: '{% if is_state("device_tracker.rasplex", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'RasPlex'
    ring:
      value_template: '{% if is_state("device_tracker.ring", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Ring Doorbell'
    lightifybridge:
      value_template: '{% if is_state("device_tracker.lightify_bridge", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Lightify Bridge'
- platform: random
  name: whitenoise
  minimum: 1
  maximum: 3
#- platform: command_line
#  name: CPU Temperature
#  scan_interval:
#    seconds: 10
#  command: "cat /sys/class/thermal/thermal_zone0/temp"
#  value_template: '{{ value | multiply(0.0018) | round(1) +32 }}'
#  unit_of_measurement: "°F"
#- platform: command_line
#  name: air_quality
#  scan_interval:
#    minutes: 10
#  command: 'curl -X GET -H "Content-type: application/json" -H "Accept: application/json" "http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=38016&distance=25&API_KEY=BB4DF57E-645A-4867-935F-3BC241441002"'
#  value_template: '{{value_json[0]["AQI"]}}'
- platform: systemmonitor
  scan_interval:
    seconds: 10
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: load_5m
- platform: mqtt
  state_topic: "smartthings/Front Door/battery"
  name: "Doorbell Battery"
- platform: dnsip
  scan_interval: 300
- platform: time_date
  display_options:
    - 'time'
