
- platform: time_date
  display_options:
    - 'time'
- platform: darksky
  api_key: !secret darksky
  latitude: !secret latitude
  longitude: !secret longitude
  forecast: 
    - 0
  monitored_conditions:
    - icon
    - daily_summary
    - summary
    - precip_probability
    - temperature
    - temperature_high
    - temperature_low
    - cloud_cover
    - uv_index
    - apparent_temperature
    - wind_speed
    - wind_bearing
    - temperature_high
    - temperature_low
- platform: template
  sensors:
    current_activity_bedroom_tv:
      friendly_name: 'Current Activity'
      value_template: >
        {% if states.media_player.vizio_smartcast_2.attributes.source == "hdmi2" %}
          Watch DirecTV
        {% elif states.media_player.vizio_smartcast_2.attributes.source == "hdmi3" %}
          Play Nintendo Switch
        {% elif states.media_player.vizio_smartcast_2.attributes.source == "cast" %}
          {{states.media_player.vizio_smartcast_2.attributes.app_name}}
        {% elif states.media_player.vizio_smartcast_2.attributes.source == "Unknown" %}
          Unknown
        {% else %}
          Power Off
        {% endif %}        
    brightness_pantry:
      value_template: >
        {% if states.light.pantry.state == 'off'%}
          0
        {% else %}
          {{states.light.pantry.attributes.brightness | int}}
        {% endif %}
    brightness_lr:
      value_template: >
        {% if states.light.living_room.state == 'off'%}
          0
        {% else %}
          {{states.light.living_room.attributes.brightness | int}}
        {% endif %}
    decimal_time:
      value_template: '{{(now().strftime("%H") | int) + (now().strftime("%M")|int / 60) | round(2)}}'
    protect_down:
      value_template: '{% if  states.sensor.downstairs_nest_protect_bedroom_battery_health.state == "Ok" and states.sensor.downstairs_nest_protect_bedroom_co_status.state == "Ok" and states.sensor.downstairs_nest_protect_bedroom_smoke_status.state == "Ok" %}Online{% elif states.sensor.kithen_nest_protect_bedroom_co_status.state == "Emergency" or states.sensor.downstairs_nest_protect_bedroom_smoke_status.state == "Emergency" %}Emergency {% elif states.sensor.downstairs_nest_protect_bedroom_battery_health.state == "Replace" %}Low Battery {% else %}Error{% endif %}'    
    protect_kitchen:
      value_template: '{% if  states.sensor.downstairs_nest_protect_kitchen_battery_health.state == "Ok" and states.sensor.downstairs_nest_protect_kitchen_co_status.state == "Ok" and states.sensor.downstairs_nest_protect_kitchen_smoke_status.state == "Ok" %}Online{% elif states.sensor.downstairs_nest_protect_kitchen_co_status.state == "Emergency" or states.sensor.downstairs_nest_protect_kitchen_smoke_status.state == "Emergency" %}Emergency {% elif states.sensor.downstairs_nest_protect_kitchen_battery_health.state == "Replace" %}Low Battery {% else %}Error{% endif %}'
    protect_up:
      value_template: '{% if  states.sensor.upstairs_nest_protect_hallway_battery_health.state == "Ok" and states.sensor.upstairs_nest_protect_hallway_co_status.state == "Ok" and states.sensor.upstairs_nest_protect_hallway_smoke_status.state == "Ok" %}Online{% elif states.sensor.kithen_nest_protect_hallway_co_status.state == "Emergency" or states.sensor.upstairs_nest_protect_hallway_smoke_status.state == "Emergency" %}Emergency {% elif states.sensor.upstairs_nest_protect_hallway_battery_health.state == "Replace" %}Low Battery {% else %}Error{% endif %}'      
    front_door:
      friendly_name: 'Front Door'
      value_template: '{% if is_state("binary_sensor.front_door", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.front_door", "off") %}mdi:door{% else %}mdi:door-open{% endif %}'
    back_door:
      friendly_name: 'Back Door'
      value_template: '{% if is_state("binary_sensor.back_door", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.back_door", "off") %}mdi:door{% else %}mdi:door-open{% endif %}'
    garage_door:
      friendly_name: 'Garage Door'
      value_template: '{% if is_state("binary_sensor.garage_door", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.garage_door", "off") %}mdi:door{% else %}mdi:door-open{% endif %}'
    front_windows:
      friendly_name: 'Front Windows'
      value_template: '{% if is_state("binary_sensor.front_windows", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.front_windows", "off") %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    back_windows:
      friendly_name: 'Back Windows'
      value_template: '{% if is_state("binary_sensor.back_windows", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.back_windows", "off") %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    bedroom_windows:
      friendly_name: 'Bedroom Windows'
      value_template: '{% if is_state("binary_sensor.bedroom_windows", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.bedroom_windows", "off") %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    downstairs_windows:
      friendly_name: 'Back Windows'
      value_template: '{% if states.binary_sensor.back_windows.state == "off" and states.binary_sensor.front_windows.state == "off" %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if states.binary_sensor.back_windows.state == "off" and states.binary_sensor.front_windows.state == "off" %}mdi:window-closed{% else %}mdi:window-open{% endif %}'
    away_toggle:
      value_template: '{% if is_state("input_boolean.disable_away_mode", "on") %}home{% else %}not_home{% endif %}'
      friendly_name: 'Away Toggle'    
    hvac_leak_sensor:
      value_template: '{% if is_state("binary_sensor.hvac_leak_sensor", "off") %}Dry{% elif is_state("binary_sensor.hvac_leak_sensor", "on") %}Wet{% endif %}'
      icon_template: '{% if is_state("binary_sensor.hvac_leak_sensor", "off") %}mdi:water-off{% elif is_state("binary_sensor.hvac_leak_sensor", "on") %}mdi:water{% endif %}'
      friendly_name: 'HVAC Leak Sensor'
    water_heater_leak_sensor:
      value_template: '{% if is_state("binary_sensor.water_heater_leak_sensor", "off") %}Dry{% elif is_state("binary_sensor.water_heater_leak_sensor", "on") %}Wet{% endif %}'
      icon_template: '{% if is_state("binary_sensor.water_heater_leak_sensor", "off") %}mdi:water-off{% elif is_state("binary_sensor.water_heater_leak_sensor", "on") %}mdi:water{% endif %}'
      friendly_name: 'Water Heater Leak Sensor' 
    tautulli_streams:
      value_template: '{{ states.sensor.tautulli.attributes.stream_count }}'
      icon_template: mdi:cloud-upload-outline
      friendly_name: 'Streams'
      unit_of_measurement: ' '
    tautulli_transcodes:
      value_template: '{{ states.sensor.tautulli.attributes.stream_count_transcode }}'
      icon_template: mdi:cloud-upload
      friendly_name: 'Transcodes'
      unit_of_measurement: ' '
    ender_3_pro_print_time_remaining:
      value_template: >
        {% set minutes = (states.sensor.ender_3_pro_time_remaining.state|int/60) | int %}{% set hours = (minutes/60) |int %}{% set minutes = minutes-(hours*60)%}{% set seconds = states.sensor.ender_3_pro_time_remaining.state|int - (minutes*60) - ((hours*60)*60) %}{%if hours==0 %}{% elif hours==1%}{{hours}} hour, {% else %}{{hours}} hours, {% endif %}{%if minutes==0 %}{% elif minutes==1%}{{minutes}} minute{% else %}{{minutes}} minutes{% endif %}{% if hours == 0 and minutes == 0 and seconds > 30 %}Less than a minute{%elif hours == 0 and minutes == 0 and seconds == 0 and states.sensor.ender_3_pro_print_job_percentage.state == "100"%}Print Complete{%elif states.sensor.ender_3_pro_time_remaining.state == "unknown" %}Calculating...{%elif hours == 0 and minutes == 0 and seconds <= 30 and states.sensor.ender_3_pro_time_remaining != "unknown" %}A few seconds{%endif%}
      friendly_name: 'Time Remaining'
    ender_3_pro_print_job_percentage:
      value_template: '{{ states.sensor.ender_3_pro_job_percentage.state|int }}'
      friendly_name: 'Job Progress'
      unit_of_measurement: '%'          
- platform: random
  name: whitenoise
  minimum: 1
  maximum: 8
- platform: mqtt
  state_topic: "plex"
  name: "Rasplex Status"
  value_template: '{{ value_json.body }}'
- platform: dnsip
  scan_interval: 300
- platform: tautulli
  api_key: !secret tautulli
  host: 10.0.0.109
  scan_interval: 5
#- platform: nws_alerts
#  zone_id: 'TNC157'
#  name: Severe Weather Alerts

- platform: plex_assistant
