- alias: Simulate Presence 1
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 8
  action:
    service: light.turn_on
    entity_id: light.living_room
    data:
      brightness: 254
      transition: 900

- alias: Simulate Presence 2
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: time
    at: '19:00:00'
  action:
    service: light.turn_on
    entity_id:
      - light.overhead_light
      - light.recessed_lights
    
- alias: Simulate Presence 3
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: time
    at: '19:45:00'
  action:
    - service: light.turn_on
      entity_id: light.chandelier
    - delay:
        seconds: 5
    - service: light.turn_off
      entity_id: light.overhead_light
      
- alias: Simulate Presence 4
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: time
    at: '20:30:00'
  action:
    - service: light.turn_off
      entity_id: 
        - light.chandelier
        - light.recessed_lights
    - delay:
        seconds: 60
    - service: light.turn_on
      entity_id: light.living_room
      data:
        brightness: 100
    - service: remote.turn_on
      entity_id: remote.living_room
      data: {"activity": "Watch DirecTV"}

- alias: Simulate Presence 5
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: time
    at: '22:30:00'
  action:
    service: light.turn_on
    entity_id: light.master_bedroom
    data:
      brightness: 150
      color_temp: 500
      transition: 60

- alias: Simulate Presence 6
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: time
    at: '23:45:00'
  action:
    - service: light.turn_off
      entity_id: light.living_room
    - service: remote.turn_off
      entity_id: remote.living_room 

- alias: Simulate Presence 7
  hide_entity: True
  initial_state: 'off'
  trigger:
    platform: time
    at: '00:15:00'
  action:
    - service: light.turn_off
      entity_id: light.master_bedroom

      
