- alias: Simulate Presence 1
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 8
  condition: 
    condition: state
    entity_id: input_boolean.simulate_presence
    state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.living_room_lights
      data:
        brightness: 254
        transition: 900
    - service: switch.turn_on
      entity_id: switch.patio_lights

- alias: Simulate Presence 2
  trigger:
    platform: time
    at: '17:45:00'
  condition: 
    condition: state
    entity_id: input_boolean.simulate_presence
    state: 'on'
  action:
    - delay: '00:{{ (range(0, 30)|random|int) }}:00'
    - service: light.turn_on
      entity_id: light.recessed_lights
    - service: switch.turn_on
      entity_id: switch.overhead_light
    
- alias: Simulate Presence 3
  trigger:
    platform: time
    at: '18:30:00'
  condition: 
    condition: state
    entity_id: input_boolean.simulate_presence
    state: 'on'
  action:
    - delay: '00:{{ (range(0, 15)|random|int) }}:00'
    - service: switch.turn_on
      entity_id: switch.chandelier
    - delay: '00:{{ (range(0, 3)|random|int) }}:{{ (range(1,59)|random|int) }}'
    - service: switch.turn_off
      entity_id: switch.overhead_light
      
- alias: Simulate Presence 4
  trigger:
    platform: time
    at: '19:15:00'
  condition: 
    condition: state
    entity_id: input_boolean.simulate_presence
    state: 'on'
  action:
    - delay: '00:{{ (range(0, 30)|random|int) }}:00'
    - service: switch.turn_off
      entity_id: switch.chandelier
    - service: light.turn_off
      entity_id: light.recessed_lights
    - delay:
        seconds: 60
    - service: light.turn_on
      entity_id: light.living_room_lights
      data:
        brightness: 100

- alias: Simulate Presence 5
  trigger:
    platform: time
    at: '21:15:00'
  condition: 
    condition: state
    entity_id: input_boolean.simulate_presence
    state: 'on'
  action:
    - delay: '00:{{ (range(0, 30)|random|int) }}:00'
    - service: light.turn_on
      entity_id: light.master_bedroom
      data:
        brightness: 150
        color_temp: 500
        transition: 60
    - service: light.turn_on
      entity_id: light.mancave_lights

- alias: Simulate Presence 6
  trigger:
    platform: time
    at: '23:45:00'
  condition: 
    condition: state
    entity_id: input_boolean.simulate_presence
    state: 'on'
  action:
    - delay: '00:{{ (range(0, 10)|random|int) }}:00'
    - delay: '00:{{ (range(0, 4)|random|int) }}:{{ (range(1,59)|random|int) }}'
    - service: light.turn_off
      entity_id: light.living_room_lights
    - service: light.turn_off
      entity_id: light.mancave_lights
    - service: switch.turn_off
      entity_id: switch.patio_lights

- alias: Simulate Presence 7
  trigger:
    platform: time
    at: '00:05:00'
  condition: 
    condition: state
    entity_id: input_boolean.simulate_presence
    state: 'on'
  action:
    - delay: '00:{{ (range(0, 15)|random|int) }}:00'
    - service: light.turn_off
      entity_id: light.master_bedroom
