- alias: Home Mode General
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
  action:
    - service: nest.set_away_mode
      data:
        away_mode: home
        structure:
          - Hidden Ridge
    - service: light.turn_on
      entity_id: 
        - light.pantry
        - light.recessed_lights
      data:
        brightness: 254
    - service: script.fan_on
    - service: media_player.turn_off
      entity_id: media_player.livingroom_assistant
    - delay: 
        seconds: 2
    - service: media_player.volume_set
      entity_id: 
        - media_player.livingroom_assistant
        - media_player.dining_room_speaker
        - media_player.kitchen_display
        - media_player.mancave_assistant
        - media_player.tristans_clock
        - media_player.crystals_clock
        - media_player.bathroom_assistant
      data: 
        volume_level: 0.4
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 8
    - condition: numeric_state
      entity_id: sensor.decimal_time
      above: 12
    - service: switch.turn_on
      entity_id: switch.patio_lights
      
