- alias: Away Mode General
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home' 
  action:
    - service: nest.set_away_mode
      data:
        away_mode: away
        structure:
          - Hidden Ridge
    - service: media_player.turn_off
      entity_id:
        - media_player.all_assistants
        - media_player.all_speakers
        - media_player.bathroom_assistant
        - media_player.bedroom_assistant
        - media_player.bedroom_speaker
        - media_player.dining_room_speaker
        - media_player.house_party_protocol
        - media_player.garage_speaker
        - media_player.kitchen_display
        - media_player.mancave_assistant
        - media_player.livingroom_assistant
        - media_player.master_suite
        - media_player.party_mode
        - media_player.bedroom_tv
    - service: script.fan_off
    - service: remote.turn_off
      entity_id: remote.livingroom
    - service: light.turn_off
      entity_id:
        - light.pantry
        - light.foyer
        - light.master_hallway
        - light.dining_room
        - group.stairway
        - light.recessed_lights
        - light.desk_lamp
    - service: switch.turn_off
      entity_id: 
        - switch.overhead_light
        - switch.chandelier
        - switch.patio_lights
    - service: cover.close_cover
      entity_id: cover.garage_door_opener
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if states.sun.sun.attributes.elevation <= 8 %}
            script.away_mode_night
          {% elif is_state('binary_sensor.rain', 'on') %}
            script.away_mode_rain
          {% else %}
            script.away_mode_day
          {% endif %}
    - service: script.lock_doors
